name: CI

on:
  pull_request:
  push:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        entry:
          - { os: ubuntu-latest, java: 11 }
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 11

      - name: Set up SBT
        uses: sbt/setup-sbt@v1

      - name: Style check
        run: sbt scalafmtCheckAll

      - name: Set SBT_OPTS
        # Needed to extend the JVM memory size to avoid OutOfMemoryError for HTML test report
        run: echo "SBT_OPTS=-Xmx2G" >> $GITHUB_ENV

      - name: Integ Test
        run: sbt integtest/integration

      - name: Upload test report
        if: always() # Ensures the artifact is saved even if tests fail
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: target/test-reports # Adjust this path if necessary

      - name: Test report - flint commons
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'target/test-reports/flint-commons/index.html'
          job_summary: true

      - name: Test report - flint core
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'target/test-reports/flint-core/index.html'
          job_summary: true

      - name: Test report - flint spark integration
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'target/test-reports/flint-spark-integration/index.html'
          job_summary: true

      - name: Test report - ppl spark integration
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'target/test-reports/ppl-spark-integration/index.html'
          job_summary: true

      - name: Test report - sql job
        uses: pavi2410/html-preview-action@v4
        with:
          html_file: 'target/test-reports/sql-job/index.html'
          job_summary: true
